[main]
    separator = "-"
    description = "A Hinode instance specifically built for testing rendering and compatibility."
    enableDarkMode = true
    enableLanguageSelectionStorage = false
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    endorse = true
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    [main.externalLinks]
        cue = false
        tab = false
    [main.build]
        transpiler = "libsass"

[debugging]
    showJS = true
    showSCSS = true
    purgeHTMLComments = false

[docs]
    github = "https://github.com/anoduck/hinode-testsite"
    release = "https://github.com/anoduck/hinode-testsite/releases/tag/"
    checkVersion = true

[home]
    sections = ["modules", "blog"]
    fullCover = true
    centerHeadline = true
    style = ""

[navigation]
    anchor = true
    logo = "logo-lg.jpg"
    color = "body"
    fixed = true
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"

[messages]
    placement = "bottom-right"

[images]
    [images.cloudinary]
        host = "cloudinary"
        account = "anoduck"

[videos]
    [videos.cloudinary]
        host = "cloudinary"
        account = "anoduck"
    [videos.youtube]
        host = "youtube"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

# toml-docs-start sections
[sections]
    [sections.modules]
        title = "Modules"
        sort = "weight"
        reverse = false
        nested = true
        cols = 3
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom"
        homepage = 3
        separator = true
    [sections.blog]
        title = "Blog"
        sort = "date"
        reverse = true
        nested = true
        cols = 3
        color = ""
        padding = "0"
        header = "full"
        footer = "none"
        orientation = "stacked"
        style = "border-0 card-zoom"
        homepage = 3
        separator = true
# toml-docs-end sections

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[style]
    primary = "#d93dce"
    secondary = "#5b44f2"
    success = "#1bf260"
    info = "#72a9f2"
    warning = "#DEC754"
    danger = "#f21f1b"
    light = "#2e29a6"
    dark = "#232073"
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    fontSizeBase = "1rem"
    purge = false

[schema]
    type = "Organization"
    name = "Anoduck"
    locale = "en-US"
    # twitter = "https://twitter.com/gethinode"
    # linkedIn = ""
    github = "https://github.com/anoduck/hinode-testsite"
    section = "blog"
    [schema.author]
        name = "Anoduck, The Anonymous Duck"
        # twitter = "https://twitter.com/markdumay"
        # linkedin = "https://www.linkedin.com/in/markdumay/"
        github = "https://github.com/anoduck"
    [schema.logo]
        url = "logo.jpg"
        width = 512
        height = 512
    [schema.image]
        url = "logo-lg.jpg"
        width = 1280
        height = 640

[opengraph]
    images = ["logo.jpg", "logo-lg.jpg", "logo-sm.jpg"]
    locale = "en_US"

[links]
    hinode = "https://gethinode.com"

[modules.fontawesome]
	skipMissing = true
